#test run
name: Call Microsoft Graph via PowerShell

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  graph-call:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscriptions: true

    - name: Run PowerShell to Call Microsoft Graph
      shell: pwsh
      run: |
        $tenantId = "${{ secrets.AZURE_TENANT_ID }}"
        $clientId = "${{ secrets.AZURE_CLIENT_ID }}"
        $scope = "https://graph.microsoft.com/.default"

        # Request a token from Azure AD
        $tokenResponse = Invoke-RestMethod -Method POST `
          -Uri "https://login.microsoftonline.com/$tenantId/oauth2/v2.0/token" `
          -Body @{
              client_id     = $clientId
              scope         = $scope
              grant_type    = "client_credentials"
              client_assertion_type = "urn:ietf:params:oauth:client-assertion-type:jwt-bearer"
              client_assertion      = "${{ steps.azure-login.outputs.accessToken }}"
          } -ContentType "application/x-www-form-urlencoded"

        $accessToken = $tokenResponse.access_token

        # Call Microsoft Graph API
        $response = Invoke-RestMethod -Uri "https://graph.microsoft.com/v1.0/users" `
          -Headers @{ Authorization = "Bearer $accessToken" }

        $response.value | ForEach-Object {
          Write-Output "User: $($_.displayName) <$($_.userPrincipalName)>"
        }
