#test run3
name: Call Microsoft Graph via PowerShell

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  graph-call:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        #subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscriptions: true

    - name: Run PowerShell to Call Microsoft Graph
      shell: pwsh
      run: |
        $tenantId = "${{ secrets.AZURE_TENANT_ID }}"
        $clientId = "${{ secrets.AZURE_CLIENT_ID }}"
        $scope = "https://graph.microsoft.com/.default"

        # Get an OIDC-based token from GitHub to Azure
        $response = az account get-access-token `
          --resource https://graph.microsoft.com/ `
          --query accessToken -o tsv

        $headers = @{
          Authorization = "Bearer $response"
        }

        # Call Graph
        $users = Invoke-RestMethod -Uri "https://graph.microsoft.com/v1.0/users" -Headers $headers
        $cas = Invoke-RestMethod -Uri "https://graph.microsoft.com/v1.0/identity/conditionalAccess/policies" -Headers $headers
        
        $users.value | ForEach-Object {
          Write-Host "$($_.displayName) <$($_.userPrincipalName)>"
        }

        # Show policies
        $cas.value | ForEach-Object {
          Write-Host "$($_.id)"
          }
